# Aus der Travis CI Dokumentation
# https://docs.travis-ci.com/user/build-stages/

jobs:
  include:
    - script: ./test 1 # uses the default stage name "test"
    - script: ./test 2
    - stage: deploy
      script: ./deploy target-1
    - script: ./deploy target-2
