#!/bin/sh

cd $TRAVIS_BUILD_DIR
mkdir build

cd $TRAVIS_BUILD_DIR/expose
pdflatex expose.tex
bibtex expose
pdflatex expose.tex
pdflatex expose.tex
cp expose.pdf ../build/expose_ba_maemecke.pdf

cd $TRAVIS_BUILD_DIR
pdflatex thesis.tex
bibtex thesis
pdflatex thesis.tex
pdflatex thesis.tex
cp thesis.pdf build/thesis_ba_maemecke.pdf
